language: node_js
node_js: '6'

before_install:
- npm install -g npm@latest

deploy:
  provider: npm
  email: npm@xuluwarrior.org
  api_key:
    secure: OzyghJu2AdxhQJ1eNaa1iasDfmSVlTTUKrmGRtGybYMgwEGysiIlJ4jPvdPGBfbLdtiXoRwKTc4mwqJWMwn17CHhkfSZrNby/PeBl0RcK6HXqKWh4paCdX6hskSLedXkJSWq991zFojZzM+EjKHL981CzwefrZYg5sIWnSyaRZduusEsHfYp2EnCrwLW8jvLV13T2ImCg60NyB2vtomZ0P8wPrGjPhEqIvJLyQ1t2lYJka3ckRTz0aMixxC3G6jYkcNuvmVYxxqHMspcVOxIfj4IdH2W7+YCRWW0HnhobAG/DQi9WVvGx6RMFe0ef9CPLsExRbgP+DjAP+JqeDEWzgKBqxPuTzdK5oPeqa/4/+g/Q/uhWrjKG7VaqJO+19pbNAeRJ7jhTl7aQOcQaZG2iwJFONURVcNYoa0qE/63n9aBzBcb11CFv6D22H28XLEQOucNEL3Qx3KlqQX67iupFJZyIJJkGxBb4tcZVB/iIM9S26w9FIou0G9YvYVJoOWHIAqx2cDn65FytO5tE3Yrjzp5bSsph0qE5HH17hVhrWlwIWOdYPOAcg1OOCmOimCGs80FLoNdZ4hkdpZays6vB2W65d9d8BDNYsCdTdwolfb4tGC9Oc6VUwwmJXRgUYGqCGxGLiS/ZkTaBsY76pgZi0xS6bk2vqcrgnPCGxi7CNs=
  on:
    tags: true
    repo: XuluWarrior/jsonresume-theme-orbit-original
